version: '3'

services:
  mongo:
    container_name: 'mongo'
    image: mongo:latest
    command: mongod --quiet
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'root'
    volumes:
      - mongo:/data/db
    ports:
      - '27016:27017'
  
  backend:
    container_name: 'backend'
    build: .
    depends_on:
      - mongo
    ports:
      - "8443:8443"

volumes:
  mongo:
